
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file: .env
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes: 
      - www:/var/www/html
    env_file: .env
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes: 
      - www:/var/www/html
    env_file: .env
    environment:
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_ADMIN_NAME=${WORDPRESS_ADMIN_NAME}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_USER_NAME=${WORDPRESS_USER_NAME}
      - WORDPRESS_USER_PASSWORD=${WORDPRESS_USER_PASSWORD}
    networks:
      - inception
    restart: always
        

networks:
  inception:
    name: inception
    
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/db
      #device: /var/lib/mysql
      # ~/data/db

  www:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wp
      #device: /var/www/html
      #~/data/wp
