version: "3"

networks:
  inception:
    name: inception

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    volumes:
      - /data/mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes: 
      - wordpress:/var/www/html
    env_file: .env
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes: 
      - wordpress:/var/www/html
    env_file: .env
    networks:
      - inception
    restart: always
        
    
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/mysql

  www:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/www/html
